
// Copyright © 2024, Julian Scheffers
// SPDX-License-Identifier: MIT



#ifndef C_KEYW_DEF
#define C_KEYW_DEF(x)
#endif

C_KEYW_DEF(_Alignas)
C_KEYW_DEF(_Alignof)
C_KEYW_DEF(_Atomic)
C_KEYW_DEF(_Bool)
C_KEYW_DEF(_Complex)
C_KEYW_DEF(_Generic)
C_KEYW_DEF(_Imaginary)
C_KEYW_DEF(_Noreturn)
C_KEYW_DEF(_Static_assert)
C_KEYW_DEF(_Thread_local)
C_KEYW_DEF(auto)
C_KEYW_DEF(break)
C_KEYW_DEF(case)
C_KEYW_DEF(char)
C_KEYW_DEF(const)
C_KEYW_DEF(continue)
C_KEYW_DEF(default)
C_KEYW_DEF(do)
C_KEYW_DEF(double)
C_KEYW_DEF(else)
C_KEYW_DEF(enum)
C_KEYW_DEF(extern)
C_KEYW_DEF(float)
C_KEYW_DEF(for)
C_KEYW_DEF(goto)
C_KEYW_DEF(if)
C_KEYW_DEF(inline)
C_KEYW_DEF(int)
C_KEYW_DEF(long)
C_KEYW_DEF(register)
C_KEYW_DEF(restrict)
C_KEYW_DEF(return)
C_KEYW_DEF(short)
C_KEYW_DEF(signed)
C_KEYW_DEF(sizeof)
C_KEYW_DEF(static)
C_KEYW_DEF(struct)
C_KEYW_DEF(switch)
C_KEYW_DEF(typedef)
C_KEYW_DEF(union)
C_KEYW_DEF(unsigned)
C_KEYW_DEF(void)
C_KEYW_DEF(volatile)
C_KEYW_DEF(while)

#undef C_KEYW_DEF
